version: 2

refs:
  - &container
    docker:
      - image: node:8.11
    working_directory: ~/repo
  - &npm_auth
    run:
      name: NPM Auth
      command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - &install
    run:
      name: Yarn Install
      command: cd source && yarn install --frozen-lockfile && npx bolt
  - &build
    run:
      name: Build
      command: cd source && yarn build
  - &test
    run:
      name: Test
      command:
        cd tests/cabbie-async-test && npm i && npm test -- chromedriver --replay ../snapshot.json &&\
        cd ../cabbie-sync-test && npm i && npm test -- chromedriver --replay ../snapshot.json

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - *npm_auth
      - *install
      - *build
      - *test

  master:
    <<: *container
    steps:
      - checkout
      - *npm_auth
      - *install
      - *build
      - *test

workflows:
  version: 2
  all:
    jobs:
      - all:
          filters:
            branches:
              ignore:
                - master
  master:
    jobs:
      - master:
          filters:
            branches:
              only: master
